// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const linkSearchResult = `-- name: LinkSearchResult :batchexec
INSERT INTO search_results (search_id, company_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkSearchResultBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type LinkSearchResultParams struct {
	SearchID  int64
	CompanyID int64
}

func (q *Queries) LinkSearchResult(ctx context.Context, arg []LinkSearchResultParams) *LinkSearchResultBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.SearchID,
			a.CompanyID,
		}
		batch.Queue(linkSearchResult, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &LinkSearchResultBatchResults{br, len(arg), false}
}

func (b *LinkSearchResultBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *LinkSearchResultBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertCompany = `-- name: UpsertCompany :batchone
INSERT INTO companies (
    osm_type, osm_id, name, category, subcategory,
    website, phone, email, instagram, facebook, vk, telegram, whatsapp,
    addr_country, addr_city, addr_street, addr_housenumber, addr_postcode,
    opening_hours, tags, lat, lon
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18,
    $19, $20, $21, $22
)
ON CONFLICT (osm_type, osm_id) DO UPDATE SET
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    website = EXCLUDED.website,
    phone = EXCLUDED.phone,
    email = EXCLUDED.email,
    instagram = EXCLUDED.instagram,
    facebook = EXCLUDED.facebook,
    vk = EXCLUDED.vk,
    telegram = EXCLUDED.telegram,
    whatsapp = EXCLUDED.whatsapp,
    addr_country = EXCLUDED.addr_country,
    addr_city = EXCLUDED.addr_city,
    addr_street = EXCLUDED.addr_street,
    addr_housenumber = EXCLUDED.addr_housenumber,
    addr_postcode = EXCLUDED.addr_postcode,
    opening_hours = EXCLUDED.opening_hours,
    tags = EXCLUDED.tags,
    lat = EXCLUDED.lat,
    lon = EXCLUDED.lon,
    updated_at = now()
RETURNING id
`

type UpsertCompanyBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertCompanyParams struct {
	OsmType         string
	OsmID           string
	Name            string
	Category        string
	Subcategory     string
	Website         string
	Phone           string
	Email           string
	Instagram       string
	Facebook        string
	Vk              string
	Telegram        string
	Whatsapp        string
	AddrCountry     string
	AddrCity        string
	AddrStreet      string
	AddrHousenumber string
	AddrPostcode    string
	OpeningHours    string
	Tags            []byte
	Lat             float64
	Lon             float64
}

// Insert a company or update it on OSM identity conflict; returns its id.
func (q *Queries) UpsertCompany(ctx context.Context, arg []UpsertCompanyParams) *UpsertCompanyBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.OsmType,
			a.OsmID,
			a.Name,
			a.Category,
			a.Subcategory,
			a.Website,
			a.Phone,
			a.Email,
			a.Instagram,
			a.Facebook,
			a.Vk,
			a.Telegram,
			a.Whatsapp,
			a.AddrCountry,
			a.AddrCity,
			a.AddrStreet,
			a.AddrHousenumber,
			a.AddrPostcode,
			a.OpeningHours,
			a.Tags,
			a.Lat,
			a.Lon,
		}
		batch.Queue(upsertCompany, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertCompanyBatchResults{br, len(arg), false}
}

func (b *UpsertCompanyBatchResults) QueryRow(f func(int, int64, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var id int64
		if b.closed {
			if f != nil {
				f(t, id, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&id)
		if f != nil {
			f(t, id, err)
		}
	}
}

func (b *UpsertCompanyBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
