// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID              int64
	OsmType         string
	OsmID           string
	Name            string
	Category        string
	Subcategory     string
	Website         string
	Phone           string
	Email           string
	Instagram       string
	Facebook        string
	Vk              string
	Telegram        string
	AddrCountry     string
	AddrCity        string
	AddrStreet      string
	AddrHousenumber string
	AddrPostcode    string
	OpeningHours    string
	Tags            []byte
	Lat             float64
	Lon             float64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Whatsapp        string
}

type Search struct {
	ID           int64
	RegionName   string
	RegionAreaID int64
	Filters      []byte
	ResultCount  int32
	CreatedAt    pgtype.Timestamptz
}

type SearchResult struct {
	SearchID  int64
	CompanyID int64
}
