// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const createSearch = `-- name: CreateSearch :one
INSERT INTO searches (region_name, region_area_id, filters, result_count)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateSearchParams struct {
	RegionName   string
	RegionAreaID int64
	Filters      []byte
	ResultCount  int32
}

func (q *Queries) CreateSearch(ctx context.Context, arg CreateSearchParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSearch,
		arg.RegionName,
		arg.RegionAreaID,
		arg.Filters,
		arg.ResultCount,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getSearch = `-- name: GetSearch :one
SELECT id, region_name, region_area_id, filters, result_count, created_at
FROM searches
WHERE id = $1
`

func (q *Queries) GetSearch(ctx context.Context, id int64) (Search, error) {
	row := q.db.QueryRow(ctx, getSearch, id)
	var i Search
	err := row.Scan(
		&i.ID,
		&i.RegionName,
		&i.RegionAreaID,
		&i.Filters,
		&i.ResultCount,
		&i.CreatedAt,
	)
	return i, err
}

const getSearchCompanies = `-- name: GetSearchCompanies :many
SELECT
    c.osm_type, c.osm_id, c.name, c.category, c.subcategory,
    c.website, c.phone, c.email, c.instagram, c.facebook, c.vk, c.telegram, c.whatsapp,
    c.addr_country, c.addr_city, c.addr_street, c.addr_housenumber, c.addr_postcode,
    c.opening_hours, c.lat, c.lon
FROM search_results sr
JOIN companies c ON c.id = sr.company_id
WHERE sr.search_id = $1
ORDER BY c.name
`

type GetSearchCompaniesRow struct {
	OsmType         string
	OsmID           string
	Name            string
	Category        string
	Subcategory     string
	Website         string
	Phone           string
	Email           string
	Instagram       string
	Facebook        string
	Vk              string
	Telegram        string
	Whatsapp        string
	AddrCountry     string
	AddrCity        string
	AddrStreet      string
	AddrHousenumber string
	AddrPostcode    string
	OpeningHours    string
	Lat             float64
	Lon             float64
}

func (q *Queries) GetSearchCompanies(ctx context.Context, searchID int64) ([]GetSearchCompaniesRow, error) {
	rows, err := q.db.Query(ctx, getSearchCompanies, searchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSearchCompaniesRow
	for rows.Next() {
		var i GetSearchCompaniesRow
		if err := rows.Scan(
			&i.OsmType,
			&i.OsmID,
			&i.Name,
			&i.Category,
			&i.Subcategory,
			&i.Website,
			&i.Phone,
			&i.Email,
			&i.Instagram,
			&i.Facebook,
			&i.Vk,
			&i.Telegram,
			&i.Whatsapp,
			&i.AddrCountry,
			&i.AddrCity,
			&i.AddrStreet,
			&i.AddrHousenumber,
			&i.AddrPostcode,
			&i.OpeningHours,
			&i.Lat,
			&i.Lon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSearches = `-- name: ListSearches :many
SELECT id, region_name, region_area_id, filters, result_count, created_at
FROM searches
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListSearchesParams struct {
	Off int32
	Lim int32
}

func (q *Queries) ListSearches(ctx context.Context, arg ListSearchesParams) ([]Search, error) {
	rows, err := q.db.Query(ctx, listSearches, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Search
	for rows.Next() {
		var i Search
		if err := rows.Scan(
			&i.ID,
			&i.RegionName,
			&i.RegionAreaID,
			&i.Filters,
			&i.ResultCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
